name: Build and Publish Package

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    timeout-minutes: 5
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@noop-inc'

      - name: Cache NPM
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install Dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_READ_TOKEN }}

      - name: Build Documentation JSON File
        run: node .github/workflows/build.js

      - name: Bump and Publish
        run: node .github/workflows/bump.js
        env:
          GITHUB_REF: ${{ github.ref }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
